/* Naam Jap v3 — clean offline-first application core. */
(() => {
  'use strict';
  const APP_VERSION = '3.0.0';
  const DB_NAME = 'naam-jap-db';
  const DB_VERSION = 1;
  const STORE = 'app';
  const KEY = 'state';
  const MALA = 108;
  const MILESTONES = [108, 1008, 10008, 108000];
  const NAV = ['home','jap','naam','profile','sankalp','settings'];
  const NAV_ICONS = {home:'⌂', jap:'◉', naam:'ॐ', profile:'◯', sankalp:'◇', settings:'⚙'};
  const I18N = {
    en: {
      appName:'Naam Jap', intro:'A peaceful space for remembering the Divine Name, one Jap at a time.', language:'Language', preferredNaam:'Preferred Jap Naam', customNaamOptional:'Custom Naam (optional)', continue:'Continue', home:'Home', jap:'Jap', naam:'Naam', profile:'Profile', sankalp:'Sankalp', settings:'Settings', todayJap:"Today's Jap", todayMala:"Today's Mala", nextMala:'Next Mala', totalJap:'Total Jap', totalMala:'Total Mala', startJap:'Start Jap', thought:'Daily Smaran', beforeJap:'Jap se pehle', beforeText:'Settle your breath, remember the Divine Name, and begin gently.', selectedNaam:'Selected Naam', session:'Session', undo:'Undo', pause:'Pause', resume:'Resume', finish:'Finish', sound:'Sound', malaComplete:'108 Jap complete — 1 Mala completed.', chooseNaam:'Choose Naam', addCustom:'Add Custom Naam', search:'Search Naam', select:'Select', favourite:'Favourite', unfavourite:'Unfavourite', daysPracticed:'Days Practiced', mostUsed:'Most-used Naam', streak:'Current Streak', history:'Sadhana History', today:'Today', yesterday:'Yesterday', sevenDays:'7 Days', thirtyDays:'30 Days', all:'All', noHistory:'No Jap history yet.', sankalpTitle:'Sankalp', createSankalp:'Create Sankalp', target:'Target Jap', deadline:'Deadline (optional)', progress:'Progress', remaining:'Remaining', active:'Active', completed:'Completed', noSankalp:'No active Sankalp.', certificates:'Certificates', unlocked:'Unlocked', locked:'Locked', exportBackup:'Export Backup', importBackup:'Import / Restore Backup', profileName:'Your Name', started:'Started', save:'Save', saved:'Saved', languageSetting:'Language', soundSetting:'Sound & Vibration', masterSound:'Master Sound', tapSound:'Tap Sound', malaSound:'Mala Completion Sound', vibration:'Vibration', tapProtection:'Tap Protection', strict:'Strict', normal:'Normal', off:'Off', volume:'Volume', display:'Display', darkMode:'Dark Mode', keepAwake:'Keep Screen Awake During Jap', data:'Data & Privacy', reset:'Reset App Data', resetWarning:'This permanently clears local Naam Jap data. Export a backup first if needed.', cancel:'Cancel', confirm:'Confirm', certificateNote:'App-generated local achievement. It is not externally verified.', downloadPrint:'Print / Save PDF', close:'Close', firstMala:'First Mala', sadhanaStep:'Sadhana Step', deepSadhana:'Deep Sadhana', naamSankalp:'Naam Sankalp', addNaamPrompt:'Enter your custom Naam', noNaamFound:'No Naam found.', dailyGoal:'Daily Goal', targetPlaceholder:'e.g. 1008', certificate:'Certificate', certFor:'Certificate for', certificateId:'Certificate ID', date:'Date', naamCount:'Naam count', stats:'Statistics', backupSuccess:'Backup exported.', restoreSuccess:'Backup restored successfully.', invalidBackup:'Invalid or incompatible backup file.', confirmRestore:'Restore this backup and replace current data?', resetDone:'App data cleared.', selected:'Selected', total:'Total', perNaam:'Naam-wise Summary', noCertificates:'No certificates unlocked yet.'
    },
    hi: {
      appName:'नाम जाप', intro:'ईश्वर के नाम का शांत स्मरण — एक-एक जाप के साथ।', language:'भाषा', preferredNaam:'पसंदीदा जाप नाम', customNaamOptional:'कस्टम नाम (वैकल्पिक)', continue:'जारी रखें', home:'होम', jap:'जाप', naam:'नाम', profile:'प्रोफ़ाइल', sankalp:'संकल्प', settings:'सेटिंग्स', todayJap:'आज का जाप', todayMala:'आज की माला', nextMala:'अगली माला', totalJap:'कुल जाप', totalMala:'कुल माला', startJap:'जाप शुरू करें', thought:'आज का स्मरण', beforeJap:'जाप से पहले', beforeText:'श्वास को शांत करें, ईश्वर के नाम का स्मरण करें और सहज भाव से शुरू करें।', selectedNaam:'चयनित नाम', session:'सत्र', undo:'वापस', pause:'रोकें', resume:'जारी रखें', finish:'समाप्त', sound:'ध्वनि', malaComplete:'108 जाप पूर्ण — 1 माला पूरी हुई।', chooseNaam:'नाम चुनें', addCustom:'कस्टम नाम जोड़ें', search:'नाम खोजें', select:'चुनें', favourite:'पसंदीदा', unfavourite:'पसंदीदा हटाएँ', daysPracticed:'जाप किए दिन', mostUsed:'सबसे अधिक जाप', streak:'वर्तमान स्ट्रीक', history:'साधना इतिहास', today:'आज', yesterday:'कल', sevenDays:'7 दिन', thirtyDays:'30 दिन', all:'सभी', noHistory:'अभी जाप इतिहास नहीं है।', sankalpTitle:'संकल्प', createSankalp:'संकल्प बनाएँ', target:'लक्ष्य जाप', deadline:'अंतिम तारीख (वैकल्पिक)', progress:'प्रगति', remaining:'बाकी', active:'सक्रिय', completed:'पूर्ण', noSankalp:'कोई सक्रिय संकल्प नहीं है।', certificates:'प्रमाणपत्र', unlocked:'प्राप्त', locked:'लॉक', exportBackup:'बैकअप एक्सपोर्ट करें', importBackup:'बैकअप इम्पोर्ट / रिस्टोर', profileName:'आपका नाम', started:'आरंभ', save:'सहेजें', saved:'सहेजा गया', languageSetting:'भाषा', soundSetting:'ध्वनि और कंपन', masterSound:'मुख्य ध्वनि', tapSound:'टैप ध्वनि', malaSound:'माला पूर्ण ध्वनि', vibration:'कंपन', tapProtection:'टैप सुरक्षा', strict:'सख्त', normal:'सामान्य', off:'बंद', volume:'वॉल्यूम', display:'दिखावट', darkMode:'डार्क मोड', keepAwake:'जाप के दौरान स्क्रीन चालू रखें', data:'डेटा और गोपनीयता', reset:'ऐप डेटा रीसेट करें', resetWarning:'यह डिवाइस पर मौजूद नाम जाप डेटा मिटा देगा। पहले बैकअप लें।', cancel:'रद्द करें', confirm:'पुष्टि करें', certificateNote:'यह ऐप द्वारा बनाया गया स्थानीय उपलब्धि प्रमाणपत्र है। इसकी बाहरी पुष्टि नहीं होती।', downloadPrint:'प्रिंट / PDF सेव करें', close:'बंद करें', firstMala:'पहली माला', sadhanaStep:'साधना चरण', deepSadhana:'गहन साधना', naamSankalp:'नाम संकल्प', addNaamPrompt:'अपना कस्टम नाम लिखें', noNaamFound:'कोई नाम नहीं मिला।', dailyGoal:'दैनिक लक्ष्य', targetPlaceholder:'जैसे 1008', certificate:'प्रमाणपत्र', certFor:'प्रमाणपत्र', certificateId:'प्रमाणपत्र आईडी', date:'तारीख', naamCount:'नाम जाप', stats:'आँकड़े', backupSuccess:'बैकअप एक्सपोर्ट हो गया।', restoreSuccess:'बैकअप सफलतापूर्वक रिस्टोर हो गया।', invalidBackup:'अमान्य या असंगत बैकअप फ़ाइल।', confirmRestore:'क्या इस बैकअप से वर्तमान डेटा बदलना है?', resetDone:'ऐप डेटा साफ़ कर दिया गया।', selected:'चयनित', total:'कुल', perNaam:'नाम के अनुसार सारांश', noCertificates:'अभी कोई प्रमाणपत्र प्राप्त नहीं हुआ।'
    }
  };
  const NAAMS = [
    ['radha','Radha','राधा','Radha'], ['radhe-radhe','Radhe Radhe','राधे राधे','Radha'], ['shri-radha','Shri Radha','श्री राधा','Radha'],
    ['krishna','Krishna','कृष्ण','Krishna'], ['govind','Govind','गोविंद','Krishna'], ['gopal','Gopal','गोपाल','Krishna'], ['shyam','Shyam','श्याम','Krishna'], ['madhav','Madhav','माधव','Krishna'],
    ['hari','Hari','हरि','Vishnu'], ['ram','Ram','राम','Ram'], ['shri-ram','Shri Ram','श्री राम','Ram'], ['siya-ram','Siya Ram','सिया राम','Ram'],
    ['om','Om','ॐ','Shiva'], ['om-namah-shivaya','Om Namah Shivaya','ॐ नमः शिवाय','Shiva'], ['shiv','Shiv','शिव','Shiva'], ['mahadev','Mahadev','महादेव','Shiva'], ['narayan','Narayan','नारायण','Vishnu'],
    ['hare-krishna','Hare Krishna Hare Krishna','हरे कृष्ण हरे कृष्ण','Maha Mantra'], ['hare-rama','Hare Rama Hare Rama','हरे राम हरे राम','Maha Mantra'],
    ['maha-mantra-krishna','Hare Krishna Hare Krishna, Krishna Krishna Hare Hare','हरे कृष्ण हरे कृष्ण, कृष्ण कृष्ण हरे हरे','Maha Mantra'],
    ['maha-mantra-rama','Hare Rama Hare Rama, Rama Rama Hare Hare','हरे राम हरे राम, राम राम हरे हरे','Maha Mantra']
  ];
  const DEFAULT_SETTINGS = { masterSound:true, tapSound:true, malaSound:true, vibration:true, volume:45, tapProtection:'normal', darkMode:false, keepAwake:true };
  const todayKey = () => new Date().toISOString().slice(0,10);
  const nowISO = () => new Date().toISOString();
  const uid = () => (crypto && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`);
  const clampInt = (n, min=0, max=Number.MAX_SAFE_INTEGER) => Number.isFinite(Number(n)) ? Math.min(max, Math.max(min, Math.floor(Number(n)))) : min;
  const esc = (s) => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const t = k => (I18N[state.lang] || I18N.en)[k] || I18N.en[k] || k;
  const fmt = n => new Intl.NumberFormat(state.lang === 'hi' ? 'en-IN' : 'en-US').format(clampInt(n));
  const defaultNaam = id => NAAMS.find(x=>x[0]===id) || NAAMS[1];
  const displayNaam = naam => state.lang === 'hi' ? (naam.hi || naam.name) : naam.name;
  function makeNaam(id,name,hi,group,custom=false) { return {id,name,hi,group,custom}; }
  function freshState() {
    const counts = {};
    NAAMS.forEach(x => counts[x[0]] = 0);
    return { schemaVersion:1, onboarded:false, lang:'en', profile:{name:'', startedAt:todayKey()}, selectedNaamId:'radhe-radhe', customNaams:[], favourites:['radhe-radhe'], counts, daily:{}, sessions:[], sankalps:[], certificates:[], settings:{...DEFAULT_SETTINGS} };
  }
  let state = freshState();
  let db;
  let saveTimer;
  let currentView = 'home';
  let historyFilter = 'all';
  let activeSession = null;
  let isPaused = false;
  let lastTapAt = 0;
  let wakeLock = null;

  function openDB() {
    return new Promise((resolve,reject) => {
      const req = indexedDB.open(DB_NAME, DB_VERSION);
      req.onupgradeneeded = () => {
        const d = req.result;
        if (!d.objectStoreNames.contains(STORE)) d.createObjectStore(STORE);
      };
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error);
    });
  }
  function dbGet() { return new Promise((res,rej)=>{ const tx=db.transaction(STORE,'readonly'); const r=tx.objectStore(STORE).get(KEY); r.onsuccess=()=>res(r.result); r.onerror=()=>rej(r.error); }); }
  function dbSet(value) { return new Promise((res,rej)=>{ const tx=db.transaction(STORE,'readwrite'); const r=tx.objectStore(STORE).put(value,KEY); r.onsuccess=()=>res(); r.onerror=()=>rej(r.error); }); }
  function normalize(raw) {
    const base=freshState(); if (!raw || typeof raw!=='object') return base;
    const s={...base,...raw, profile:{...base.profile,...(raw.profile||{})}, settings:{...base.settings,...(raw.settings||{})}};
    s.counts={...base.counts,...(raw.counts||{})}; s.daily=raw.daily&&typeof raw.daily==='object'?raw.daily:{};
    s.customNaams=Array.isArray(raw.customNaams)?raw.customNaams.filter(x=>x&&x.id&&x.name):[];
    s.favourites=Array.isArray(raw.favourites)?raw.favourites.filter(Boolean):[];
    s.sessions=Array.isArray(raw.sessions)?raw.sessions:[]; s.sankalps=Array.isArray(raw.sankalps)?raw.sankalps:[]; s.certificates=Array.isArray(raw.certificates)?raw.certificates:[];
    if (!NAAMS.some(x=>x[0]===s.selectedNaamId) && !s.customNaams.some(x=>x.id===s.selectedNaamId)) s.selectedNaamId='radhe-radhe';
    return s;
  }
  async function persist(immediate=false) { clearTimeout(saveTimer); if (immediate) return dbSet(state); saveTimer=setTimeout(()=>dbSet(state).catch(()=>{}),80); }
  function allNaams() { return [...NAAMS.map(x=>makeNaam(x[0],x[1],x[2],x[3])),...state.customNaams.map(x=>makeNaam(x.id,x.name,x.hi||x.name,x.group||'Custom',true))]; }
  function selectedNaam() { return allNaams().find(x=>x.id===state.selectedNaamId) || allNaams()[1]; }
  function countFor(id) { return clampInt(state.counts[id]||0); }
  function dailyFor(date=todayKey()) { return state.daily[date] || {}; }
  function dailyTotal(date=todayKey()) { return Object.values(dailyFor(date)).reduce((a,b)=>a+clampInt(b),0); }
  function totalJap() { return allNaams().reduce((a,n)=>a+countFor(n.id),0); }
  function totalMala() { return Math.floor(totalJap()/MALA); }
  function dateLabel(k) { const d=new Date(k+'T00:00:00'); return new Intl.DateTimeFormat(state.lang==='hi'?'hi-IN':'en-IN',{day:'numeric',month:'short',year:'numeric'}).format(d); }
  function milestoneLabel(n) { return ({108:t('firstMala'),1008:t('sadhanaStep'),10008:t('deepSadhana'),108000:t('naamSankalp')})[n] || `${fmt(n)} ${t('naamCount')}`; }
  function progressPct(a,b) { return b>0 ? Math.min(100,(a/b)*100) : 0; }
  function toast(msg) { const el=document.createElement('div'); el.className='toast'; el.textContent=msg; document.getElementById('toast-region').appendChild(el); setTimeout(()=>el.remove(),2300); }
  function setView(view) { if(!NAV.includes(view)) view='home'; currentView=view; document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); document.getElementById(`view-${view}`).classList.add('active'); renderTopbar(); renderNav(); renderView(); window.scrollTo({top:0,behavior:'instant'}); }
  function renderTopbar(){ const title=t(currentView); document.getElementById('topbar-title').textContent=title; document.getElementById('topbar-action').style.visibility=currentView==='home'?'visible':'hidden'; }
  function renderNav(){ document.getElementById('bottom-nav').innerHTML=NAV.map(n=>`<button class="nav-item ${currentView===n?'active':''}" data-nav="${n}" aria-label="${esc(t(n))}"><span class="nav-icon" aria-hidden="true">${NAV_ICONS[n]}</span><span class="nav-label">${esc(t(n))}</span></button>`).join(''); }
  function renderView(){ ({home:renderHome,jap:renderJap,naam:renderNaam,profile:renderProfile,sankalp:renderSankalp,settings:renderSettings}[currentView])(); }
  function renderHome(){ const id=selectedNaam().id, today=dailyFor(), nToday=countForDailyNaam(today,id), next=today[id]?today[id]%MALA:0, total=countFor(id); const active=state.sankalps.find(s=>s.status==='active'); document.getElementById('view-home').innerHTML=`
    <div class="card hero-card"><div class="eyebrow">${esc(t('selectedNaam'))}</div><div class="naam-display">${esc(displayNaam(selectedNaam()))}</div><div class="stats-grid"><div class="stat"><div class="label">${esc(t('todayJap'))}</div><div class="value">${fmt(dailyTotal())}</div></div><div class="stat"><div class="label">${esc(t('todayMala'))}</div><div class="value">${fmt(Math.floor(dailyTotal()/MALA))}</div></div></div><div class="section-title">${esc(t('nextMala'))}</div><div class="progress-track"><div class="progress-fill" style="width:${(next/MALA)*100}%"></div></div><div class="progress-meta"><span>${fmt(next)} / ${MALA}</span><span>${fmt(MALA-next)} ${esc(t('remaining'))}</span></div><button class="primary-btn full" data-action="start-jap">${esc(t('startJap'))}</button></div>
    <div class="section-title">${esc(t('stats'))}</div><div class="stats-grid"><div class="stat"><div class="label">${esc(t('totalJap'))}</div><div class="value">${fmt(total)}</div></div><div class="stat"><div class="label">${esc(t('totalMala'))}</div><div class="value">${fmt(Math.floor(total/MALA))}</div></div></div>
    ${active?`<div class="section-title">${esc(t('sankalpTitle'))}</div><div class="card"><div class="row"><strong>${esc(naamNameById(active.naamId))}</strong><span>${fmt(active.progress)} / ${fmt(active.target)}</span></div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" style="width:${progressPct(active.progress,active.target)}%"></div></div></div>`:''}
    <div class="section-title">${esc(t('thought'))}</div><div class="card thought"><span class="quote-mark">“</span> ${esc(state.lang==='hi'?'नाम स्मरण मन को स्थिरता और सरलता की ओर ले जाने का एक शांत अभ्यास है।':'Naam Smaran is a gentle practice of bringing the mind back to a peaceful remembrance.')}</div>
    <div class="section-title">${esc(t('beforeJap'))}</div><div class="card muted">${esc(t('beforeText'))}</div>`; }
  function countForDailyNaam(day,id){return clampInt(day[id]||0);}
  function renderJap(){ if(!activeSession){ document.getElementById('view-jap').innerHTML=`<div class="card jap-wrap"><div class="session-badge">${esc(t('selectedNaam'))}</div><div class="naam-display">${esc(displayNaam(selectedNaam()))}</div><p class="muted">${esc(t('beforeText'))}</p><button class="primary-btn full" data-action="start-session">${esc(t('startJap'))}</button></div>`; return; }
    const n=selectedNaam(); const session=activeSession; const current=countFor(n.id); const malaProgress=current%MALA; document.getElementById('view-jap').innerHTML=`<div class="jap-wrap"><div class="jap-header"><button class="secondary-btn" data-action="exit-session">← ${esc(t('home'))}</button><span class="session-badge">${esc(isPaused?t('pause'):t('session'))}</span><button class="secondary-btn" data-action="toggle-sound" aria-label="${esc(t('sound'))}">🔊</button></div><div class="eyebrow">${esc(t('selectedNaam'))}</div><div class="naam-display">${esc(displayNaam(n))}</div><div class="jap-counter" id="session-count">${fmt(session.count)}</div><div class="jap-sub">${esc(t('totalJap'))}: ${fmt(current)} · ${esc(t('totalMala'))}: ${fmt(Math.floor(current/MALA))}</div><div class="progress-track" style="margin:18px 8px 0"><div class="progress-fill" style="width:${(malaProgress/MALA)*100}%"></div></div><div class="progress-meta"><span>${fmt(malaProgress)} / ${MALA}</span><span>${fmt(MALA-malaProgress)} ${esc(t('remaining'))}</span></div><button id="jap-tap" class="jap-button" aria-label="${esc(displayNaam(n))}">${esc(state.lang==='hi'?(n.hi||n.name):n.name)}</button><div class="jap-controls"><button data-action="undo">↶ ${esc(t('undo'))}</button><button data-action="pause">${isPaused?'▶ '+esc(t('resume')):'Ⅱ '+esc(t('pause'))}</button><button class="finish" data-action="finish">✓ ${esc(t('finish'))}</button></div></div>`; }
  function renderNaam(){ const filter=document.getElementById('naam-search')?.value||''; const q=filter.trim().toLowerCase(); const groups={}; allNaams().filter(n=>(n.name+' '+n.hi).toLowerCase().includes(q)).forEach(n=>(groups[n.group]??=[]).push(n)); const body=Object.entries(groups).map(([group,items])=>`<div class="section-title">${esc(group)}</div><div class="list">${items.map(n=>`<div class="list-item"><div class="list-main"><div class="list-name">${esc(displayNaam(n))}</div><div class="list-meta">${fmt(countFor(n.id))} ${esc(t('naamCount'))} · ${fmt(Math.floor(countFor(n.id)/MALA))} ${esc(t('totalMala'))}</div></div><button class="icon-action ${state.favourites.includes(n.id)?'active':''}" data-fav="${esc(n.id)}" aria-label="${esc(state.favourites.includes(n.id)?t('unfavourite'):t('favourite'))}">${state.favourites.includes(n.id)?'★':'☆'}</button><button class="secondary-btn" data-select-naam="${esc(n.id)}">${state.selectedNaamId===n.id?esc(t('selected')):esc(t('select'))}</button></div>`).join('')}</div>`).join(''); document.getElementById('view-naam').innerHTML=`<div class="card"><div class="row"><strong>${esc(t('chooseNaam'))}</strong><button class="primary-btn" data-action="add-custom">+ ${esc(t('addCustom'))}</button></div><div class="field-group"><input id="naam-search" maxlength="80" placeholder="${esc(t('search'))}" value="${esc(filter)}"></div></div>${body||`<div class="empty">${esc(t('noNaamFound'))}</div>`}`; }
  function renderProfile(){ const total=totalJap(), days=Object.keys(state.daily).filter(k=>dailyTotal(k)>0).length; const rows=allNaams().filter(n=>countFor(n.id)>0).sort((a,b)=>countFor(b.id)-countFor(a.id)).slice(0,10); document.getElementById('view-profile').innerHTML=`<div class="card hero-card"><div class="row"><div><div class="eyebrow">${esc(t('profile'))}</div><h2 style="margin:5px 0">${esc(state.profile.name||'—')}</h2><div class="muted">${esc(t('started'))}: ${esc(dateLabel(state.profile.startedAt))}</div></div><span class="brand-mark small" aria-hidden="true">ॐ</span></div></div><div class="section-title">${esc(t('stats'))}</div><div class="stats-grid"><div class="stat"><div class="label">${esc(t('totalJap'))}</div><div class="value">${fmt(total)}</div></div><div class="stat"><div class="label">${esc(t('totalMala'))}</div><div class="value">${fmt(Math.floor(total/MALA))}</div></div><div class="stat"><div class="label">${esc(t('daysPracticed'))}</div><div class="value">${fmt(days)}</div></div><div class="stat"><div class="label">${esc(t('streak'))}</div><div class="value">${fmt(calcStreak())}</div></div></div><div class="section-title">${esc(t('perNaam'))}</div><div class="card">${rows.length?rows.map(n=>`<div class="row" style="padding:8px 0;border-bottom:1px solid var(--border)"><span>${esc(displayNaam(n))}</span><strong>${fmt(countFor(n.id))}</strong></div>`).join(''):`<div class="empty">${esc(t('noHistory'))}</div>`}</div><div class="section-title">${esc(t('history'))}</div><div class="card"><div class="tabs">${[['today','today'],['yesterday','yesterday'],['7','sevenDays'],['30','thirtyDays'],['all','all']].map(([v,k])=>`<button class="tab ${historyFilter===v?'active':''}" data-history="${v}">${esc(t(k))}</button>`).join('')}</div>${renderHistory()}</div><div class="section-title">${esc(t('certificates'))}</div><div class="list">${renderCertificatesCards()}</div>`; }
  function renderHistory(){ const keys=Object.keys(state.daily).sort().reverse().filter(k=>{ if(historyFilter==='all')return true; const d=(Date.now()-new Date(k+'T00:00:00').getTime())/86400000; return historyFilter==='today'?k===todayKey():historyFilter==='yesterday'?k===new Date(Date.now()-86400000).toISOString().slice(0,10):d<(Number(historyFilter)+1); }); if(!keys.length)return `<div class="empty">${esc(t('noHistory'))}</div>`; return `<div class="table-list">${keys.slice(0,60).map(k=>{const entries=Object.entries(state.daily[k]||{}).filter(([,v])=>clampInt(v)>0);return `<div class="history-item"><div><strong>${esc(dateLabel(k))}</strong><div class="list-meta">${entries.map(([id,v])=>`${esc(naamNameById(id))} — ${fmt(v)}`).join('<br>')}</div></div><strong>${fmt(dailyTotal(k))}</strong></div>`}).join('')}</div>`; }
  function renderCertificatesCards(){ if(!state.certificates.length)return `<div class="empty">${esc(t('noCertificates'))}</div>`; return state.certificates.slice().reverse().map(c=>`<div class="list-item"><div class="list-main"><div class="list-name">${esc(milestoneLabel(c.milestone))}</div><div class="list-meta">${esc(naamNameById(c.naamId))} · ${esc(dateLabel(c.date))}</div></div><button class="secondary-btn" data-certificate="${esc(c.id)}">${esc(t('certificate'))}</button></div>`).join(''); }
  function renderSankalp(){ const active=state.sankalps.filter(s=>s.status==='active'); document.getElementById('view-sankalp').innerHTML=`<div class="card hero-card"><div class="row"><div><div class="eyebrow">${esc(t('sankalpTitle'))}</div><h2 style="margin:5px 0">${esc(t('sankalpTitle'))}</h2></div><button class="primary-btn" data-action="new-sankalp">+ ${esc(t('createSankalp'))}</button></div></div>${active.length?active.map(s=>`<div class="section-title">${esc(naamNameById(s.naamId))}</div><div class="card"><div class="row"><strong>${fmt(s.progress)} / ${fmt(s.target)}</strong><span>${progressPct(s.progress,s.target).toFixed(1)}%</span></div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" style="width:${progressPct(s.progress,s.target)}%"></div></div><div class="progress-meta"><span>${fmt(Math.max(0,s.target-s.progress))} ${esc(t('remaining'))}</span><span>${s.deadline?esc(dateLabel(s.deadline)):''}</span></div></div>`).join(''):`<div class="empty">${esc(t('noSankalp'))}</div>`}<div class="section-title">${esc(t('certificates'))}</div><div class="list">${renderCertificatesCards()}</div>`; }
  function renderSettings(){ const s=state.settings; document.getElementById('view-settings').innerHTML=`<div class="section-title">${esc(t('profile'))}</div><div class="card form-grid"><label>${esc(t('profileName'))}<input id="profile-name" maxlength="80" value="${esc(state.profile.name)}"></label><button class="primary-btn" data-action="save-profile">${esc(t('save'))}</button></div><div class="section-title">${esc(t('languageSetting'))}</div><div class="card choice-grid two"><button class="choice-btn ${state.lang==='hi'?'active':''}" data-setting-lang="hi">हिन्दी</button><button class="choice-btn ${state.lang==='en'?'active':''}" data-setting-lang="en">English</button></div><div class="section-title">${esc(t('soundSetting'))}</div><div class="card">${toggleRow('masterSound',t('masterSound'),s.masterSound)}${toggleRow('tapSound',t('tapSound'),s.tapSound)}${toggleRow('malaSound',t('malaSound'),s.malaSound)}${toggleRow('vibration',t('vibration'),s.vibration)}<div class="toggle-row"><span>${esc(t('volume'))}</span><div class="range-row"><input id="volume-range" type="range" min="0" max="100" value="${s.volume}"><strong id="volume-value">${s.volume}</strong></div></div></div><div class="section-title">${esc(t('tapProtection'))}</div><div class="card choice-grid"><button class="choice-btn ${s.tapProtection==='strict'?'active':''}" data-protection="strict">${esc(t('strict'))}</button><button class="choice-btn ${s.tapProtection==='normal'?'active':''}" data-protection="normal">${esc(t('normal'))}</button><button class="choice-btn ${s.tapProtection==='off'?'active':''}" data-protection="off">${esc(t('off'))}</button></div><div class="section-title">${esc(t('display'))}</div><div class="card">${toggleRow('darkMode',t('darkMode'),s.darkMode)}${toggleRow('keepAwake',t('keepAwake'),s.keepAwake)}</div><div class="section-title">${esc(t('data'))}</div><div class="card stack"><button class="secondary-btn" data-action="export">${esc(t('exportBackup'))}</button><button class="secondary-btn" data-action="import">${esc(t('importBackup'))}</button><div class="notice">${esc(t('resetWarning'))}</div><button class="secondary-btn danger-btn" data-action="reset">${esc(t('reset'))}</button></div>`; }
  function toggleRow(key,label,value){ return `<div class="toggle-row"><span>${esc(label)}</span><label class="toggle"><input type="checkbox" data-setting="${key}" ${value?'checked':''}><span class="slider"></span></label></div>`; }
  function naamNameById(id){ const n=allNaams().find(x=>x.id===id); return n?displayNaam(n):id; }
  function calcStreak(){ let d=new Date(); let streak=0; while(true){const k=d.toISOString().slice(0,10);if(dailyTotal(k)<=0)break;streak++;d.setDate(d.getDate()-1);}return streak; }
  function updateSankalpsAndCertificates(naamId){ state.sankalps.forEach(s=>{ if(s.status==='active'){ s.progress=countFor(s.naamId); if(s.progress>=s.target)s.status='completed'; }}); MILESTONES.forEach(m=>{ if(countFor(naamId)>=m && !state.certificates.some(c=>c.naamId===naamId&&c.milestone===m)){ const cert={id:uid(),naamId,milestone:m,date:todayKey(),issuedAt:nowISO(),name:state.profile.name||'Naam Jap Sadhak'}; state.certificates.push(cert); setTimeout(()=>toast(`${milestoneLabel(m)} — ${t('unlocked')}`),0); }}); }
  function playTone(kind='tap'){ const s=state.settings;if(!s.masterSound || (kind==='tap'&&!s.tapSound)||(kind==='mala'&&!s.malaSound))return; try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=kind==='mala'?660:420;g.gain.value=(s.volume/100)*0.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(kind==='mala'?.22:.055));}catch(e){}}
  function vibrate(ms=20){if(state.settings.vibration&&navigator.vibrate)navigator.vibrate(ms);}
  function maybeWake(){ if(!state.settings.keepAwake||!('wakeLock' in navigator))return; navigator.wakeLock.request('screen').then(w=>wakeLock=w).catch(()=>{}); }
  function releaseWake(){ if(wakeLock){wakeLock.release().catch(()=>{});wakeLock=null;} }
  function startSession(){ activeSession={id:uid(),naamId:state.selectedNaamId,count:0,startedAt:nowISO()};isPaused=false;maybeWake();setView('jap'); }
  function registerJap(){ if(!activeSession||isPaused)return; const now=performance.now(); const guard=state.settings.tapProtection==='strict'?180:state.settings.tapProtection==='normal'?70:0; if(now-lastTapAt<guard)return; lastTapAt=now; const id=activeSession.naamId; activeSession.count++; state.counts[id]=countFor(id)+1; const day=todayKey(); state.daily[day]??={}; state.daily[day][id]=countForDailyNaam(state.daily[day],id)+1; const newTotal=state.counts[id]; updateSankalpsAndCertificates(id); persist(); playTone('tap'); vibrate(10); const btn=document.getElementById('jap-tap'); if(btn){btn.classList.remove('tap');void btn.offsetWidth;btn.classList.add('tap');} if(newTotal%MALA===0){playTone('mala');vibrate(70);toast(t('malaComplete'));} updateJapLive(); }
  function updateJapLive(){const n=selectedNaam(), c=document.getElementById('session-count');if(c)c.textContent=fmt(activeSession?.count||0);const pf=document.querySelector('#view-jap .progress-fill');if(pf)pf.style.width=`${((countFor(n.id)%MALA)/MALA)*100}%`;const metas=document.querySelectorAll('#view-jap .progress-meta');if(metas[0])metas[0].innerHTML=`<span>${fmt(countFor(n.id)%MALA)} / ${MALA}</span><span>${fmt(MALA-(countFor(n.id)%MALA))} ${esc(t('remaining'))}</span>`;}
  function undo(){ if(!activeSession||activeSession.count<=0)return; const id=activeSession.naamId; activeSession.count--; state.counts[id]=Math.max(0,countFor(id)-1); const day=todayKey(); if(state.daily[day]?.[id]){state.daily[day][id]=Math.max(0,state.daily[day][id]-1);if(state.daily[day][id]===0)delete state.daily[day][id];} state.sankalps.forEach(s=>{if(s.status==='completed'&&s.progress-1<s.target)s.status='active';s.progress=countFor(s.naamId);}); persist(); updateJapLive(); }
  function finishSession(){ if(!activeSession)return; if(activeSession.count>0)state.sessions.push({...activeSession,finishedAt:nowISO()}); activeSession=null;isPaused=false;releaseWake();persist(true);setView('home'); }
  function exitSession(){activeSession=null;isPaused=false;releaseWake();setView('home');}
  function addCustom(){ const name=prompt(t('addNaamPrompt')); if(!name)return; const clean=name.trim().slice(0,80);if(!clean)return;const id='custom-'+uid();state.customNaams.push({id,name:clean,hi:clean,group:'Custom'});state.counts[id]=0;state.selectedNaamId=id;state.favourites.push(id);persist(true);renderView();toast(t('saved')); }
  function createSankalp(){ const n=selectedNaam(); showModal(`<h2>${esc(t('createSankalp'))}</h2><div class="form-grid"><label>${esc(t('chooseNaam'))}<select id="s-naam">${allNaams().map(x=>`<option value="${esc(x.id)}" ${x.id===n.id?'selected':''}>${esc(displayNaam(x))}</option>`).join('')}</select></label><label>${esc(t('target'))}<input id="s-target" type="number" min="1" step="1" value="1008" placeholder="${esc(t('targetPlaceholder'))}"></label><label>${esc(t('deadline'))}<input id="s-deadline" type="date" min="${todayKey()}"></label></div><div class="modal-actions"><button class="secondary-btn" data-modal-close>${esc(t('cancel'))}</button><button class="primary-btn" data-action="save-sankalp">${esc(t('save'))}</button></div>`); }
  function saveSankalp(){const id=document.getElementById('s-naam').value,target=clampInt(document.getElementById('s-target').value,1);if(!target)return;const deadline=document.getElementById('s-deadline').value||null;state.sankalps.push({id:uid(),naamId:id,target,progress:countFor(id),deadline,status:countFor(id)>=target?'completed':'active',createdAt:nowISO()});persist(true);closeModal();renderSankalp();toast(t('saved'));}
  function showModal(html){document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`;}
  function closeModal(){document.getElementById('modal-root').innerHTML='';}
  function certificateModal(c){showModal(`<div class="certificate"><div class="cert-title">${esc(t('appName'))}</div><div class="cert-sub">${esc(t('certificate'))}</div><div>${esc(t('certFor'))}</div><div class="cert-name">${esc(c.name)}</div><div class="cert-meta"><strong>${esc(naamNameById(c.naamId))}</strong><br>${esc(milestoneLabel(c.milestone))}<br>${fmt(c.milestone)} ${esc(t('naamCount'))}<br>${esc(t('date'))}: ${esc(dateLabel(c.date))}</div><div class="cert-id">${esc(t('certificateId'))}: ${esc(c.id)}</div></div><div class="notice" style="margin-top:12px">${esc(t('certificateNote'))}</div><div class="modal-actions"><button class="secondary-btn" data-modal-close>${esc(t('close'))}</button><button class="primary-btn" data-action="print-certificate">${esc(t('downloadPrint'))}</button></div>`); }
  function printCertificate(){const cert=document.querySelector('.certificate');if(!cert)return;const w=window.open('','_blank');if(!w){toast('Allow pop-ups to print.');return;}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Naam Jap Certificate</title><style>body{margin:0;padding:40px;font-family:system-ui;color:#16332f}.certificate{max-width:700px;margin:auto;background:linear-gradient(145deg,#fff,#f0f9f5 60%,#fbf3df);border:8px double #c9a75e;border-radius:10px;padding:60px 35px;text-align:center}.cert-title{font-size:36px;font-weight:900;color:#176c61}.cert-sub{color:#80672d;font-weight:800;letter-spacing:.12em;text-transform:uppercase;margin:8px 0 30px}.cert-name{font-size:30px;font-weight:900;margin:20px 0}.cert-meta{line-height:1.9;color:#4c605c}.cert-id{margin-top:25px;font-size:11px;overflow-wrap:anywhere;color:#6c7975}@media print{body{padding:0}}</style></head><body>${cert.outerHTML}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250);}
  function exportBackup(){const payload={format:'Naam Jap Backup',version:APP_VERSION,schemaVersion:state.schemaVersion,exportedAt:nowISO(),data:state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`naam-jap-backup-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(t('backupSuccess'));}
  function importBackup(){const input=document.createElement('input');input.type='file';input.accept='application/json,.json';input.onchange=()=>{const file=input.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p||p.format!=='Naam Jap Backup'||!p.data||typeof p.data!=='object')throw new Error('bad');if(!confirm(t('confirmRestore')))return;state=normalize(p.data);persist(true).then(()=>{applyTheme();setView(currentView);toast(t('restoreSuccess'));});}catch(e){toast(t('invalidBackup'));}};r.readAsText(file);};input.click();}
  function resetData(){if(!confirm(t('resetWarning')))return;state=freshState();activeSession=null;releaseWake();persist(true).then(()=>{applyTheme();showOnboarding();toast(t('resetDone'));});}
  function applyTheme(){document.documentElement.dataset.theme=state.settings.darkMode?'dark':'light'; if(state.settings.darkMode){document.documentElement.style.setProperty('--bg','#0e1e1b');document.documentElement.style.setProperty('--surface','#142824');document.documentElement.style.setProperty('--surface-2','#1a3731');document.documentElement.style.setProperty('--text','#eaf7f3');document.documentElement.style.setProperty('--muted','#a5b9b4');document.documentElement.style.setProperty('--border','#28443e');}else{document.documentElement.style.cssText='';}}
  function updateI18nOnboarding(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.documentElement.lang=state.lang;}
  function showOnboarding(){document.getElementById('main').classList.add('hidden');document.getElementById('onboarding').classList.remove('hidden');const sel=document.getElementById('onboarding-naam');sel.innerHTML=allNaams().map(n=>`<option value="${esc(n.id)}">${esc(displayNaam(n))}</option>`).join('');sel.value=state.selectedNaamId;updateI18nOnboarding();document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));}
  function enterApp(){document.getElementById('onboarding').classList.add('hidden');document.getElementById('main').classList.remove('hidden');applyTheme();setView('home');}
  async function init(){ try{db=await openDB();const saved=await dbGet();if(saved)state=normalize(saved);}catch(e){state=normalize(state);} applyTheme();setTimeout(()=>{document.getElementById('splash')?.remove(); if(!state.onboarded)showOnboarding();else enterApp();},1250); }

  document.addEventListener('click', e=>{
    const nav=e.target.closest('[data-nav]');if(nav){setView(nav.dataset.nav);return;}
    const lang=e.target.closest('[data-lang]');if(lang){state.lang=lang.dataset.lang;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));document.getElementById('onboarding-naam').innerHTML=allNaams().map(n=>`<option value="${esc(n.id)}">${esc(displayNaam(n))}</option>`).join('');return;}
    const setLang=e.target.closest('[data-setting-lang]');if(setLang){state.lang=setLang.dataset.settingLang;document.documentElement.lang=state.lang;persist();renderSettings();renderNav();renderTopbar();return;}
    const action=e.target.closest('[data-action]')?.dataset.action;
    if(action==='start-jap'||action==='start-session'){startSession();return;} if(action==='exit-session'){exitSession();return;} if(action==='undo'){undo();return;} if(action==='pause'){isPaused=!isPaused;renderJap();return;} if(action==='finish'){finishSession();return;} if(action==='toggle-sound'){state.settings.masterSound=!state.settings.masterSound;persist();renderJap();return;} if(action==='add-custom'){addCustom();return;} if(action==='new-sankalp'){createSankalp();return;} if(action==='save-sankalp'){saveSankalp();return;} if(action==='save-profile'){state.profile.name=(document.getElementById('profile-name')?.value||'').trim().slice(0,80);persist(true);toast(t('saved'));return;} if(action==='export'){exportBackup();return;} if(action==='import'){importBackup();return;} if(action==='reset'){resetData();return;} if(action==='print-certificate'){printCertificate();return;}
    const sel=e.target.closest('[data-select-naam]');if(sel){state.selectedNaamId=sel.dataset.selectNaam;persist();renderNaam();toast(t('saved'));return;}
    const fav=e.target.closest('[data-fav]');if(fav){const id=fav.dataset.fav;state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];persist();renderNaam();return;}
    const hist=e.target.closest('[data-history]');if(hist){historyFilter=hist.dataset.history;renderProfile();return;}
    const cert=e.target.closest('[data-certificate]');if(cert){const c=state.certificates.find(x=>x.id===cert.dataset.certificate);if(c)certificateModal(c);return;}
    if(e.target.closest('[data-modal-close]')){closeModal();return;}
    const prot=e.target.closest('[data-protection]');if(prot){state.settings.tapProtection=prot.dataset.protection;persist();renderSettings();return;}
  });
  document.addEventListener('input', e=>{if(e.target.id==='naam-search'){renderNaam();document.getElementById('naam-search')?.focus();}if(e.target.id==='volume-range'){state.settings.volume=clampInt(e.target.value,0,100);const v=document.getElementById('volume-value');if(v)v.textContent=state.settings.volume;persist();}});
  document.addEventListener('change', e=>{const key=e.target.dataset.setting;if(key){state.settings[key]=e.target.checked;persist();if(key==='darkMode')applyTheme();}});
  document.addEventListener('click', e=>{if(e.target.id==='onboarding-continue'){const custom=document.getElementById('onboarding-custom').value.trim().slice(0,80);if(custom){const id='custom-'+uid();state.customNaams.push({id,name:custom,hi:custom,group:'Custom'});state.counts[id]=0;state.selectedNaamId=id;}else state.selectedNaamId=document.getElementById('onboarding-naam').value;state.onboarded=true;state.profile.startedAt=state.profile.startedAt||todayKey();persist(true).then(enterApp);}});
  document.addEventListener('pointerdown', e=>{if(e.target.id==='jap-tap')registerJap();});
  document.addEventListener('keydown', e=>{if(e.key===' '&&currentView==='jap'&&activeSession){e.preventDefault();registerJap();}});
  window.addEventListener('beforeunload',()=>{if(activeSession&&activeSession.count>0){state.sessions.push({...activeSession,finishedAt:nowISO(),interrupted:true});dbSet(state).catch(()=>{});}});
  navigator.storage?.persist?.().catch?.(()=>{});
  init();
})();
